# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0002_auto_20161214_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='comp_type',
            new_name='matchup_type',
        ),
        migrations.AddField(
            model_name='league',
            name='privacy_type',
            field=models.IntegerField(choices=[(1, 'private'), (2, 'public')], default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='roster',
            field=models.ManyToManyField(related_name='team_set', through='leagues.LeagueMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_captain', to=settings.AUTH_USER_MODEL),
        ),
    ]
