# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 05:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20170108_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='commissioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_leagues', to=settings.AUTH_USER_MODEL),
        ),
    ]
