# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_auto_20170108_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_key', models.CharField(max_length=40)),
                ('key_expiration', models.DateTimeField()),
                ('request_type', models.IntegerField(choices=[(1, 'invite'), (2, 'request')])),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
            ],
        ),
        migrations.AddField(
            model_name='leaguemember',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'active'), (3, 'inactive')], default=1),
        ),
        migrations.AddField(
            model_name='leaguemember',
            name='pending',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.LeagueRequests'),
        ),
    ]
