# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_auto_20170111_1227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeagueRequests',
            new_name='LeagueRequest',
        ),
    ]
