# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_auto_20170128_2349'),
        ('invitations', '0003_auto_20151126_1523'),
        ('leagues', '0008_auto_20170125_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaguePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'inactive')], default=1)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('invite_type', models.IntegerField(choices=[(1, 'league'), (2, 'team'), (3, 'open')], default=1)),
                ('approved', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='leaguemember',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='leaguemember',
            name='division',
        ),
        migrations.RemoveField(
            model_name='leaguemember',
            name='league',
        ),
        migrations.RemoveField(
            model_name='leaguemember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='leaguemember',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='pendingmember',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='pendingmember',
            name='division',
        ),
        migrations.RemoveField(
            model_name='pendingmember',
            name='invite',
        ),
        migrations.RemoveField(
            model_name='pendingmember',
            name='league',
        ),
        migrations.RemoveField(
            model_name='pendingmember',
            name='team',
        ),
        migrations.RemoveField(
            model_name='pendingmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='league',
            name='league_members',
        ),
        migrations.RemoveField(
            model_name='league',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='team',
            name='creation_datetime',
        ),
        migrations.RemoveField(
            model_name='team',
            name='roster',
        ),
        migrations.AlterField(
            model_name='league',
            name='commissioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_leagues', to='profile.PlayerProfile'),
        ),
        migrations.AlterField(
            model_name='leaguedivision',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='leagues.League'),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_captain', to='profile.PlayerProfile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='league', chained_model_field='league', null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.LeagueDivision'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='leagues.League'),
        ),
        migrations.DeleteModel(
            name='LeagueMember',
        ),
        migrations.DeleteModel(
            name='PendingMember',
        ),
        migrations.AddField(
            model_name='pendingplayer',
            name='division',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='league', chained_model_field='league', null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.LeagueDivision'),
        ),
        migrations.AddField(
            model_name='pendingplayer',
            name='invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_players', to='invitations.Invitation'),
        ),
        migrations.AddField(
            model_name='pendingplayer',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='leagues.League'),
        ),
    ]
