# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_auto_20170128_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='players',
            field=models.ManyToManyField(related_name='league_set', through='leagues.LeaguePlayer', to='profile.PlayerProfile'),
        ),
    ]
