# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_auto_20170130_1013'),
        ('leagues', '0011_auto_20170130_1013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PendingPlayer',
            new_name='LeagueInvite',
        ),
        migrations.RemoveField(
            model_name='league',
            name='pending_players',
        ),
        migrations.AddField(
            model_name='league',
            name='invitees',
            field=models.ManyToManyField(related_name='invited_leagues', through='leagues.LeagueInvite', to='profile.PlayerProfile'),
        ),
    ]
