# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20170212_2327'),
        ('leagues', '0012_auto_20170202_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='game_type',
        ),
        migrations.AddField(
            model_name='league',
            name='games',
            field=models.ManyToManyField(blank=True, to='games.Game'),
        ),
    ]
