# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 13:20
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_auto_20170223_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueinvite',
            name='team',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='league', chained_model_field='league', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_invites', to='leagues.Team'),
        ),
    ]
