# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0016_auto_20170223_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='matchup_type',
            field=models.IntegerField(choices=[(1, 'individual'), (2, 'team')], default=1),
        ),
    ]
