# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0018_auto_20170224_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueplayer',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
