from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^new/$', views.new_league, name="new_league"),
    url(r'^(?P<pk>[0-9]{1,9})/$', views.LeagueView.as_view(), name="league"),
    url(r'^(?P<pk>[0-9]{1,9})/edit/$', views.edit_league, name="edit_league"),
    url(r'^(?P<pk>[0-9]{1,9})/delete/$', views.delete_league, name='delete_league'),
    url(r'^(?P<pk>[0-9]{1,9})/invite/$', views.league_invite, name="league_invite"),
    url(r'^(?P<pk>[0-9]{1,9})/invite/(?P<pk2>[0-9]{1,9})/approve/$',
        views.approve_league_invite, name="approve_league_invite"),
    url(r'^(?P<pk>[0-9]{1,9})/invite/(?P<pk2>[0-9]{1,9})/accept/$',
        views.accept_league_invite, name="accept_league_invite"),
    url(r'^(?P<pk>[0-9]{1,9})/invite/(?P<pk2>[0-9]{1,9})/delete/$',
        views.delete_league_invite, name="delete_league_invite"),
    url(r'^(?P<pk>[0-9]{1,9})/add_team/$', views.add_team, name="add_team"),
    url(r'^(?P<pk>[0-9]{1,9})/manage_signup/$', views.manage_league_signup, name="manage_league_signup"),
    url(r'^(?P<pk>[0-9]{1,9})/join/$', views.join_league, name="join_league"),
    url(r'^(?P<pk>[0-9]{1,9})/withdraw/$', views.league_withdraw, name="league_withdraw"),
    url(r'^(?P<pk>[0-9]{1,9})/(?P<key>[\d\w]{40})/signup/$', views.league_signup, name="league_signup"),
    url(r'^(?P<pk>[0-9]{1,9})/competitions/$', views.league_competitions, name="league_competitions"),
    url(r'^(?P<pk>[0-9]{1,9})/manage_players/$', views.league_manage_players, name="league_manage_players"),
    url(r'^(?P<pk>[0-9]{1,9})/manage_teams/$', views.manage_teams, name="manage_teams"),
    url(r'^teams/(?P<pk>[0-9]{1,9})/$', views.TeamView.as_view(), name="team"),
    url(r'^teams/(?P<pk>[0-9]{1,9})/edit/$', views.edit_team, name="edit_team"),
    url(r'^teams/(?P<pk>[0-9]{1,9})/invite/$', views.team_invite, name="team_invite"),
    url(r'^teams/(?P<pk>[0-9]{1,9})/join/$', views.join_team, name="join_team"),
    url(r'^teams/(?P<pk>[0-9]{1,9})/delete/$', views.delete_team, name="delete_team"),
    url(r'^teams/(?P<pk>[0-9]{1,9})/upcoming_matchups/$',
        views.team_upcoming_matchups, name='team_upcoming_matchups'),
    url(r'^teams/(?P<pk>[0-9]{1,9})/matchup_results/$',
        views.team_matchups_results, name='team_matchup_results'),
    url(r'^teams/(?P<pk>[0-9]{1,9})/competitions/$', views.team_competitions, name="team_competitions"),
    url(r'^teams/(?P<pk>[0-9]{1,9})/manage_players/$', views.team_manage_players, name="team_manage_players"),
]
