# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=6)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('zip_code', models.IntegerField()),
                ('user_image', models.FileField(null=True, upload_to='/static/img/profile/user')),
                ('bg_image', models.FileField(null=True, upload_to='/static/img/profile/bg')),
                ('rating', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ('user',),
            },
        ),
    ]
