# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 22:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='abbrev',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bg_image',
            field=models.FileField(null=True, upload_to='dublyou/static/img/profile/bg'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 10 digits allowed.", regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.FileField(null=True, upload_to='dublyou/static/img/profile/user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
