# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20161214_1042'),
        ('player_profile', '0003_auto_20161214_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_key',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_state',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hometown_city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hometown_state',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_type',
            field=models.IntegerField(choices=[(1, 'private'), (2, 'public')], default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_game',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_game',
            field=models.ManyToManyField(to='games.GameType'),
        ),
    ]
