# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 16:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gametype',
            old_name='comp_type',
            new_name='matchup_type',
        ),
        migrations.RenameField(
            model_name='gametype',
            old_name='comp_per_team',
            new_name='players_per_team',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='game_rules',
        ),
        migrations.AddField(
            model_name='gamerule',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamerule',
            name='rule_type',
            field=models.IntegerField(choices=[(1, 'scoring'), (2, 'competitors'), (3, 'other')]),
        ),
        migrations.AlterField(
            model_name='gametype',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
