# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 05:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_auto_20161214_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('game_class', models.IntegerField(choices=[(1, 'Sport'), (2, 'Race'), (3, 'Board Game'), (4, 'Card Game'), (5, 'Video Game'), (6, 'Bar Game'), (7, 'Other')])),
                ('game_subclass', models.CharField(max_length=25)),
                ('matchup_type', models.IntegerField(blank=True, choices=[(1, 'individual'), (2, 'team')], null=True)),
                ('players_per_team', models.IntegerField(blank=True, null=True)),
                ('inventor', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='gametype',
            old_name='game_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='gametype',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gametype',
            name='inventor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gamerule',
            name='game_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_rules', to='games.GameType'),
        ),
        migrations.AlterField(
            model_name='gamerule',
            name='rule',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gametype',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gametype',
            name='matchup_type',
            field=models.IntegerField(blank=True, choices=[(1, 'individual'), (2, 'team')], null=True),
        ),
    ]
