# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20170212_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametype',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='gamerule',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='gamevenue',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='gamevenue',
            name='venue_name',
        ),
        migrations.AddField(
            model_name='gamerule',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_rules', to='games.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamevenue',
            name='games',
            field=models.ManyToManyField(to='games.Game'),
        ),
        migrations.AddField(
            model_name='gamevenue',
            name='name',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
