# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0026_auto_20170212_2327'),
        ('leagues', '0013_auto_20170212_2327'),
        ('games', '0004_auto_20170212_2327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameType',
        ),
    ]
