# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-21 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_delete_gametype'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_class',
            new_name='game_type',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_subclass',
        ),
        migrations.AddField(
            model_name='gamestat',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='games.Game'),
        ),
    ]
