# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20170223_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/games'),
        ),
    ]
