# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='profile_image',
            new_name='game_image',
        ),
    ]
