# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import dublyou.utils


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20170224_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_image',
            field=models.ImageField(blank=True, null=True, upload_to=dublyou.utils.upload_to_path),
        ),
    ]
