# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0003_auto_20170228_0859'),
        ('competitions', '0033_auto_20170224_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchupVideo',
            fields=[
                ('video_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='competitions.Matchup')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_on_server', models.FileField(help_text='Temporary file on server for                                               using in `direct upload` from                                               your server to youtube', null=True, upload_to='videos')),
            ],
        ),
    ]
