# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchupCompetitor',
            new_name='MatchupMember',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='competition_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='matchup',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='competitorinfo',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_set', to='leagues.League'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
