# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_remove_season_season_playoffs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='name',
            new_name='competition_name',
        ),
        migrations.AlterField(
            model_name='competitorinfo',
            name='matchup_type',
            field=models.IntegerField(choices=[(1, 'individual'), (2, 'team')], default=1),
        ),
        migrations.AlterField(
            model_name='competitorinfo',
            name='signup_method',
            field=models.IntegerField(choices=[(1, 'invite'), (2, 'league'), (3, 'individual signup'), (4, 'team signup')], default=1),
        ),
    ]
