# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_auto_20170111_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorinfo',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_set', to='leagues.League'),
        ),
        migrations.AlterField(
            model_name='competitorinfo',
            name='players_per_team',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
