# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20161214_1042'),
        ('leagues', '0007_auto_20170111_1230'),
        ('competitions', '0008_auto_20170112_0305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('competition_name',), 'verbose_name': 'Competition', 'verbose_name_plural': 'Competitions'},
        ),
        migrations.AlterModelOptions(
            name='competitorinfo',
            options={'ordering': ('competition',), 'verbose_name': 'Competitor Information', 'verbose_name_plural': 'Competitor Information'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ('competition',), 'verbose_name': 'Series', 'verbose_name_plural': 'Series'},
        ),
        migrations.RemoveField(
            model_name='competitorinfo',
            name='league',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='matchupmember',
            name='accepted',
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='league',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='leagues.League'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.GameVenue'),
        ),
        migrations.AddField(
            model_name='matchupmember',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='competitorinfo',
            name='competition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='comp_info', serialize=False, to='competitions.Competition'),
        ),
        migrations.AlterField(
            model_name='competitorinfo',
            name='split_teams',
            field=models.IntegerField(blank=True, choices=[(1, 'random'), (2, 'manual')], null=True),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='child_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.GameVenue'),
        ),
        migrations.AlterField(
            model_name='matchupmember',
            name='seed',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='child_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='series',
            name='tourney_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.TourneyRound'),
        ),
        migrations.AlterField(
            model_name='tourneyround',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourney_rounds', to='competitions.Tournament'),
        ),
    ]
