# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 05:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_auto_20170125_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(max_length=30)),
                ('stat_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('invite_type', models.IntegerField(choices=[(1, 'competition'), (2, 'team'), (3, 'open')], default=1)),
                ('approved', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionSignUpPage',
            fields=[
                ('verification_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('msg_image', models.ImageField(blank=True, null=True, upload_to='media/img/competitions/signup')),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[-\\s\\.\\w\\d]{1,30}$')])),
                ('competitor_type', models.IntegerField(choices=[(1, 'individual'), (2, 'team')], default=1)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'verified')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorSeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MatchupCompetitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_outcome', models.IntegerField(choices=[(1, 'winner'), (2, 'loser')], null=True)),
                ('dependent_type', models.IntegerField(choices=[(1, 'matchup'), (2, 'series'), (4, 'season')], null=True)),
                ('dependent_id', models.IntegerField(null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('seed', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='StatMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('parent_type', models.IntegerField(choices=[(0, 'Competition'), (1, 'Matchup'), (2, 'Series'), (3, 'Tournament'), (4, 'Season')])),
                ('child_id', models.IntegerField()),
                ('child_type', models.IntegerField(choices=[(1, 'Competitor'), (2, 'PlayerProfile'), (3, 'CompetitionTeam'), (4, 'Team'), (5, 'LeaguePlayer')])),
            ],
        ),
        migrations.RemoveField(
            model_name='competitorinfo',
            name='competition',
        ),
        migrations.AlterUniqueTogether(
            name='matchupmember',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='matchupmember',
            name='matchup',
        ),
        migrations.RemoveField(
            model_name='matchupmember',
            name='player',
        ),
        migrations.RemoveField(
            model_name='matchupmember',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='subteam',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='subteam',
            name='matchup',
        ),
        migrations.RemoveField(
            model_name='subteam',
            name='member',
        ),
        migrations.RemoveField(
            model_name='subteam',
            name='team',
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('name',), 'verbose_name': 'Competition', 'verbose_name_plural': 'Competitions'},
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='competition_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='competition_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='competition_name',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='players',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='teams',
        ),
        migrations.AddField(
            model_name='competition',
            name='abbrev',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
