# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 16:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_auto_20170130_1013'),
        ('competitions', '0011_auto_20170128_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='abbrev',
        ),
        migrations.AddField(
            model_name='competitor',
            name='invitees',
            field=models.ManyToManyField(related_name='team_competition_invites', through='competitions.CompetitionInvite', to='profile.PlayerProfile'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_competitions', to='profile.PlayerProfile'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[-\\s\\.\\w\\d]{1,30}$')]),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.IntegerField(choices=[(0, 'incomplete'), (1, 'upcoming'), (2, 'dependency'), (3, 'in progress'), (4, 'finished'), (5, 'if necessary'), (6, 'overdue')], default=1),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_set', to='competitions.Competition'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_teams', to='leagues.Team'),
        ),
    ]
