# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_auto_20170201_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitionsignuppage',
            old_name='Competition',
            new_name='competition',
        ),
    ]
