# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_auto_20170201_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitioninvite',
            name='team',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='competition', chained_model_field='competition', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_invites', to='competitions.Competitor'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='parent_id',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='parent_type',
            field=models.IntegerField(choices=[(1, 'matchup'), (2, 'series'), (3, 'tournament'), (4, 'season'), (5, 'olympics')], editable=False, null=True),
        ),
    ]
