# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-04 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_auto_20170202_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olympic_events', to='competitions.Competition'),
        ),
    ]
