# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_auto_20170204_0504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchup',
            options={'ordering': ('competition', 'child_num'), 'verbose_name': 'Matchup', 'verbose_name_plural': 'Matchups'},
        ),
        migrations.AlterModelOptions(
            name='matchupcompetitor',
            options={'ordering': ('matchup__competition', 'matchup__date', 'matchup__child_num', 'seed'), 'verbose_name': 'Matchup', 'verbose_name_plural': 'Matchups'},
        ),
        migrations.AlterField(
            model_name='matchup',
            name='witness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='witness', to='profile.PlayerProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='competitorseed',
            unique_together=set([('competition', 'competitor')]),
        ),
    ]
