# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_auto_20170206_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchupcompetitor',
            options={'ordering': ('matchup__competition', 'matchup__date', 'matchup__child_num', 'seed'), 'verbose_name': 'Matchup Competitor', 'verbose_name_plural': 'Matchup Competitors'},
        ),
        migrations.AddField(
            model_name='tourneyround',
            name='slots',
            field=models.IntegerField(null=True),
        ),
    ]
