# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_auto_20170130_1013'),
        ('competitions', '0018_auto_20170206_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxstat',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profile.PlayerProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxstat',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchupcompetitor',
            name='place',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchupcompetitor',
            name='matchup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mc_set', to='competitions.Matchup'),
        ),
        migrations.AlterField(
            model_name='statmember',
            name='child_type',
            field=models.IntegerField(choices=[(0, 'Competitor'), (1, 'PlayerProfile'), (2, 'Team'), (3, 'LeaguePlayer')]),
        ),
        migrations.AlterField(
            model_name='statmember',
            name='parent_type',
            field=models.IntegerField(choices=[(0, 'Competition'), (1, 'Matchup'), (2, 'Series'), (3, 'Tournament'), (4, 'Season'), (5, 'Olympics'), (6, 'MatchupCompetitor')]),
        ),
        migrations.AlterUniqueTogether(
            name='boxstat',
            unique_together=set([('stat_member', 'stat_name', 'added_by')]),
        ),
        migrations.AlterUniqueTogether(
            name='matchupcompetitor',
            unique_together=set([('matchup', 'competitor')]),
        ),
    ]
