# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0019_auto_20170208_1052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchupcompetitor',
            unique_together=set([('matchup', 'competitor')]),
        ),
    ]
