# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0021_auto_20170208_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchupcompetitor',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchup_competitors', to='competitions.Competitor'),
        ),
        migrations.AlterField(
            model_name='matchupcompetitor',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='matchupcompetitor',
            unique_together=set([('matchup', 'dependent_outcome', 'dependent_type', 'dependent_id', 'seed'), ('matchup', 'competitor')]),
        ),
    ]
