# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0023_auto_20170209_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='competitors',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='competitors',
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.IntegerField(choices=[(0, 'incomplete'), (1, 'upcoming'), (2, 'dependency'), (3, 'pending'), (4, 'finished'), (5, 'if necessary'), (6, 'unnecessary')], default=1),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='status',
            field=models.IntegerField(choices=[(0, 'incomplete'), (1, 'upcoming'), (2, 'dependency'), (3, 'pending'), (4, 'finished'), (5, 'if necessary'), (6, 'unnecessary')], default=0),
        ),
        migrations.AlterField(
            model_name='season',
            name='status',
            field=models.IntegerField(choices=[(0, 'incomplete'), (1, 'upcoming'), (2, 'dependency'), (3, 'pending'), (4, 'finished'), (5, 'if necessary'), (6, 'unnecessary')], default=0),
        ),
        migrations.AlterField(
            model_name='series',
            name='status',
            field=models.IntegerField(choices=[(0, 'incomplete'), (1, 'upcoming'), (2, 'dependency'), (3, 'pending'), (4, 'finished'), (5, 'if necessary'), (6, 'unnecessary')], default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.IntegerField(choices=[(0, 'incomplete'), (1, 'upcoming'), (2, 'dependency'), (3, 'pending'), (4, 'finished'), (5, 'if necessary'), (6, 'unnecessary')], default=0),
        ),
    ]
