# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20170212_2316'),
        ('competitions', '0025_auto_20170211_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='game_type',
        ),
        migrations.AddField(
            model_name='competition',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='favorite_game',
            field=models.ManyToManyField(blank=True, to='games.Game'),
        ),
    ]
