# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0027_auto_20170216_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='competitions.Competition'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.IntegerField(choices=[(0, 'incomplete'), (1, 'upcoming'), (2, 'dependency'), (3, 'pending'), (4, 'finished'), (5, 'if necessary'), (6, 'unnecessary')], default=0),
        ),
        migrations.AlterField(
            model_name='competitioninvite',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_invites', to='competitions.Competitor'),
        ),
    ]
