# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-21 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0028_auto_20170218_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='split_teams',
            field=models.IntegerField(choices=[(1, 'random'), (2, 'manual')], default=2),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.IntegerField(choices=[(0, 'incomplete'), (1, 'upcoming'), (2, 'dependency'), (3, 'pending'), (4, 'finished'), (5, 'if necessary'), (6, 'unnecessary'), (7, 'deleted')], default=0),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='status',
            field=models.IntegerField(choices=[(0, 'incomplete'), (1, 'upcoming'), (2, 'dependency'), (3, 'pending'), (4, 'finished'), (5, 'if necessary'), (6, 'unnecessary'), (7, 'deleted')], default=0),
        ),
        migrations.AlterField(
            model_name='season',
            name='status',
            field=models.IntegerField(choices=[(0, 'incomplete'), (1, 'upcoming'), (2, 'dependency'), (3, 'pending'), (4, 'finished'), (5, 'if necessary'), (6, 'unnecessary'), (7, 'deleted')], default=0),
        ),
        migrations.AlterField(
            model_name='series',
            name='status',
            field=models.IntegerField(choices=[(0, 'incomplete'), (1, 'upcoming'), (2, 'dependency'), (3, 'pending'), (4, 'finished'), (5, 'if necessary'), (6, 'unnecessary'), (7, 'deleted')], default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.IntegerField(choices=[(0, 'incomplete'), (1, 'upcoming'), (2, 'dependency'), (3, 'pending'), (4, 'finished'), (5, 'if necessary'), (6, 'unnecessary'), (7, 'deleted')], default=0),
        ),
    ]
