# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0029_auto_20170221_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='split_teams',
            field=models.IntegerField(choices=[(1, 'manual'), (2, 'random')], default=1),
        ),
    ]
