# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0016_auto_20170223_0720'),
        ('competitions', '0031_auto_20170223_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(related_name='team_competitions', through='competitions.Competitor', to='leagues.Team'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_competitors', to='leagues.Team'),
        ),
    ]
