# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import dublyou.apps.profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_auto_20170224_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to=dublyou.apps.profile.models.Profile.upload_to_path),
        ),
    ]
