# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20161214_1042'),
        ('profile', '0002_auto_20161204_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_zip',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.GameType'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hometown_zip',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
