# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 14:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20170224_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '(xxx) xxx-xxxx'. Up to 10 digits allowed.", regex='^\\([0-9]{3}\\) [0-9]{3}-[0-9]{4}$')]),
        ),
    ]
