# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20161222_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(null=True, upload_to='img/profile/user'),
        ),
    ]
