# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20161222_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(null=True, upload_to='media/img/profile/user'),
        ),
    ]
