# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 15:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20170104_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='abbrev',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 10 digits allowed.", regex='^\\d{10}$')]),
        ),
    ]
