# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 16:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_auto_20170128_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='abbrev',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='bg_image',
            field=models.FileField(blank=True, null=True, upload_to='dublyou/static/img/profile/bg'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='current_city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='current_state',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='current_zip',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='favorite_game',
            field=models.ManyToManyField(blank=True, to='games.GameType'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_playerprofile_friends_+', to='profile.PlayerProfile'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='hometown_city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='hometown_state',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='hometown_zip',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 10 digits allowed.", regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/profile/user'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
