# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_auto_20170130_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='favorite_game',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='rating',
        ),
    ]
