# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 03:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_auto_20170209_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='profile_type',
            field=models.IntegerField(choices=[(1, 'player')], default=1),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '(xxx) xxx-xxxx'. Up to 10 digits allowed.", regex='^([0-9]{3}) [0-9]{3}-[0-9]{4}$')]),
        ),
    ]
