# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 03:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0014_auto_20170211_2123'),
    ]

    operations = [
        migrations.RenameModel("PlayerProfile", "Profile")
    ]
