from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.get_competitions, name='competitions'),
    url(r'^new/(?:(?P<field>competition_type)/(?P<competition_type>[1-5])/)?$',
        views.new_competition, name="new_competition"),
    url(r'^new/(?:(?P<field>league)/(?P<league>[0-9]{1,9})/)?$',
        views.new_competition, name="new_competition"),
    url(r'^(?P<pk>[0-9]{1,9})/$', views.CompetitionView.as_view(), name='competition'),
    url(r'^(?P<pk>[0-9]{1,9})/edit/$', views.edit_competition, name='edit_competition'),
    url(r'^(?P<pk>[0-9]{1,9})/delete/$', views.delete_competition, name='delete_competition'),
    url(r'^(?P<pk>[0-9]{1,9})/invite/$', views.competition_invite, name='competition_invite'),
    url(r'^(?P<pk>[0-9]{1,9})/invite/(?P<pk2>[0-9]{1,9})/approve/$',
        views.approve_competition_invite, name="approve_competition_invite"),
    url(r'^(?P<pk>[0-9]{1,9})/invite/(?P<pk2>[0-9]{1,9})/accept/$',
        views.accept_competition_invite, name="accept_competition_invite"),
    url(r'^(?P<pk>[0-9]{1,9})/invite/(?P<pk2>[0-9]{1,9})/delete/$',
        views.delete_competition_invite, name="delete_competition_invite"),
    url(r'^(?P<pk>[0-9]{1,9})/manage_signup/$', views.manage_competition_signup, name="manage_competition_signup"),
    url(r'^(?P<pk>[0-9]{1,9})/manage_competitors/$', views.manage_competitors, name="manage_competitors"),
    url(r'^(?P<pk>[0-9]{1,9})/join/$', views.join_competition, name="join_competition"),
    url(r'^(?P<pk>[0-9]{1,9})/withdraw/$', views.competition_withdraw, name="competition_withdraw"),
    url(r'^(?P<pk>[0-9]{1,9})/(?P<key>[\d\w]{40})/signup/$', views.competition_signup, name="competition_signup"),
    url(r'^(?P<pk>[0-9]{1,9})/add_event/$', views.add_event, name='add_event'),
    url(r'^(?P<pk>[0-9]{1,9})/manage_events/$', views.manage_events, name='manage_events'),
    url(r'^(?P<pk>[0-9]{1,9})/create_matchups/$', views.create_matchups, name='create_matchups'),
    url(r'^(?P<pk>[0-9]{1,9})/upcoming_matchups/$', views.upcoming_matchups, name='competition_upcoming_matchups'),
    url(r'^(?P<pk>[0-9]{1,9})/matchup_results/$', views.matchups_results, name='competition_matchup_results'),
    url(r'^(?P<pk>[0-9]{1,9})/standings/$', views.competition_standings, name='competition_standings'),
    url(r'^(?P<pk>[0-9]{1,9})/bracket/$', views.competition_bracket, name='competition_bracket'),
    url(r'^matchups/(?P<pk>[0-9]{1,9})/$', views.MatchupView.as_view(), name='matchup'),
    url(r'^matchups/(?P<pk>[0-9]{1,9})/edit/$', views.edit_matchup, name='edit_matchup'),
    url(r'^matchups/(?P<pk>[0-9]{1,9})/upload_video/$', views.matchup_video_upload, name='upload_matchup_video'),
    url(r'^matchups/(?P<pk>[0-9]{1,9})/videos/$', views.matchup_videos, name='matchup_videos'),
    url(r'^matchups/(?P<pk>[0-9]{1,9})/manage_result/$', views.manage_result, name='manage_result'),
    url(r'^competitors/(?P<pk>[0-9]{1,9})/$', views.competitor, name='competitor'),
    url(r'^competitors/(?P<pk>[0-9]{1,9})/edit/$', views.edit_competitor, name='edit_competitor'),
    url(r'^competitors/(?P<pk>[0-9]{1,9})/invite/$', views.competitor_invite, name='competitor_invite'),
    url(r'^competitors/(?P<pk>[0-9]{1,9})/join/$', views.join_competitor, name="join_competitor"),
    url(r'^competitors/(?P<pk>[0-9]{1,9})/upcoming_matchups/$',
        views.competitor_upcoming_matchups, name='competitor_upcoming_matchups'),
    url(r'^competitors/(?P<pk>[0-9]{1,9})/matchup_results/$',
        views.competitor_matchups_results, name='competitor_matchup_results'),
    url(r'^competitors/(?P<pk>[0-9]{1,9})/manage_players/$',
        views.competitor_manage_players, name='competitor_manage_players'),
]
